spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  security:
    # 匿名接口，不需要认证授权
    patterns:
      - /addData/**
      - /login/**
      - /register/**
      - /forget/**
      - /getdata/**
      - /getList/**
      - /personalCenterData/**
      - /articleComment/**
      - /register/**
      - /login/**
      - /reset/**
      - /write/**
      - /articleSearch/**

  datasource:
    url: jdbc:mysql://localhost:3306/defect_management
    username: root
    password: root




logging:
  level:
    com.back.assessment: debug
